// SPDX-License-Identifier: GPL-3.0-or-later
const fs = require("fs");
const http = require("http");
const os = require("os");
const path = require("path");

const home = os.homedir();
const config = process.env.XDG_CONFIG_HOME || path.join(home, ".config");
const cache = process.env.XDG_CACHE_HOME || path.join(home, ".cache");
const palettePath = path.join(cache, "ryoku", "colors.json");
const comfyDir = path.join(config, "spicetify", "Themes", "Comfy");
const colorPath = path.join(comfyDir, "color.ini");
const basePath = path.join(comfyDir, "color.ini.spiceflow-base");
const port = Number(process.env.SPICEFLOW_PORT || 47616);

const roles = {
  text: "onSurface",
  subtext: "onSurfaceVariant",
  main: "background",
  "main-elevated": "surfaceContainer",
  "main-transition": "surface",
  highlight: "surfaceContainerHigh",
  "highlight-elevated": "surfaceContainerHighest",
  sidebar: "surfaceContainerLow",
  player: "background",
  card: "surfaceContainer",
  shadow: "shadow",
  "selected-row": "onSurface",
  button: "primary",
  "button-active": "primaryContainer",
  "button-disabled": "outlineVariant",
  "tab-active": "surfaceContainerHigh",
  notification: "tertiary",
  "notification-error": "error",
  misc: "surfaceVariant",
  "play-button": "primary",
  "play-button-active": "primaryContainer",
  "progress-fg": "secondary",
  "progress-bg": "surfaceVariant",
  heart: "error",
  "pagelink-active": "tertiary",
  "radio-btn-active": "primary",
};

function palette() {
  return JSON.parse(fs.readFileSync(palettePath, "utf8"));
}

function render() {
  if (!fs.existsSync(basePath) || !fs.existsSync(palettePath)) return;
  const colors = palette();
  const body = fs.readFileSync(basePath, "utf8");
  const lines = [
    "[wal16]",
    "; Generated by Spiceflow from Ryoku's live wallpaper palette.",
    ...Object.entries(roles).map(([name, role]) => {
      const value = colors[role];
      if (!/^#[0-9a-f]{6}$/i.test(value || "")) throw new Error(`missing palette role ${role}`);
      return `${name.padEnd(19)}= ${value}`;
    }),
  ];
  const section = `${lines.join("\n")}\n`;
  const sectionPattern = /^\[wal16\][\s\S]*?(?=^\[[^\]]+\]\s*$|(?![\s\S]))/m;
  const replaced = sectionPattern.test(body)
    ? body.replace(sectionPattern, section)
    : `${body.trimEnd()}\n\n${section}`;
  const temporary = `${colorPath}.spiceflow-tmp`;
  fs.writeFileSync(temporary, replaced);
  fs.renameSync(temporary, colorPath);
}

let timer;
fs.watchFile(palettePath, { interval: 500 }, () => {
  clearTimeout(timer);
  timer = setTimeout(() => {
    try { render(); } catch (error) { console.error(`render: ${error.message}`); }
  }, 100);
});

try { render(); } catch (error) { console.error(`initial render: ${error.message}`); }

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Private-Network": "true",
};

http.createServer((request, response) => {
  if (request.method === "OPTIONS") return response.writeHead(204, cors).end();
  if (!request.url.startsWith("/colors.json")) return response.writeHead(404).end();
  try {
    const data = fs.readFileSync(palettePath);
    response.writeHead(200, {
      ...cors,
      "Cache-Control": "no-store",
      "Content-Type": "application/json",
    });
    response.end(data);
  } catch (_) {
    response.writeHead(503, cors).end();
  }
}).listen(port, "127.0.0.1", () => {
  console.log(`Spiceflow listening on http://127.0.0.1:${port}`);
});
