// SPDX-License-Identifier: GPL-3.0-or-later
const fs = require("fs");
const http = require("http");
const os = require("os");
const path = require("path");

const home = os.homedir();
const config = process.env.XDG_CONFIG_HOME || path.join(home, ".config");
const cache = process.env.XDG_CACHE_HOME || path.join(home, ".cache");
const ryokuPalettePath = path.join(cache, "ryoku", "colors.json");
const pywalPalettePath = path.join(cache, "wal", "colors.json");
const requestedSource = process.env.SPICEFLOW_PALETTE || "auto";
const comfyDir = path.join(config, "spicetify", "Themes", "Comfy");
const colorPath = path.join(comfyDir, "color.ini");
const basePath = path.join(comfyDir, "color.ini.spiceflow-base");
const port = Number(process.env.SPICEFLOW_PORT || 47616);

const roles = {
  text: "onSurface",
  subtext: "onSurfaceVariant",
  main: "background",
  "main-elevated": "surfaceContainer",
  "main-transition": "surface",
  highlight: "surfaceContainerHigh",
  "highlight-elevated": "surfaceContainerHighest",
  sidebar: "surfaceContainerLow",
  player: "background",
  card: "surfaceContainer",
  shadow: "shadow",
  "selected-row": "onSurface",
  button: "primary",
  "button-active": "primaryContainer",
  "button-disabled": "outlineVariant",
  "tab-active": "surfaceContainerHigh",
  notification: "tertiary",
  "notification-error": "error",
  misc: "surfaceVariant",
  "play-button": "primary",
  "play-button-active": "primaryContainer",
  "progress-fg": "secondary",
  "progress-bg": "surfaceVariant",
  heart: "error",
  "pagelink-active": "tertiary",
  "radio-btn-active": "primary",
};

function hex(value, fallback) {
  return /^#[0-9a-f]{6}$/i.test(value || "") ? value : fallback;
}

function pywalToMaterial(document) {
  const colors = document.colors || {};
  const special = document.special || {};
  const color = (number, fallback) => hex(colors[`color${number}`], fallback);
  const background = hex(special.background, color(0, "#121212"));
  const foreground = hex(special.foreground, color(15, "#ffffff"));
  return {
    background,
    onSurface: foreground,
    onSurfaceVariant: color(7, foreground),
    surface: background,
    surfaceContainerLow: color(0, background),
    surfaceContainer: color(1, background),
    surfaceContainerHigh: color(5, color(8, background)),
    surfaceContainerHighest: color(13, color(5, background)),
    shadow: color(8, "#000000"),
    primary: color(6, foreground),
    primaryContainer: color(14, color(6, foreground)),
    outlineVariant: color(8, color(7, foreground)),
    secondary: color(10, color(2, foreground)),
    tertiary: color(3, color(11, foreground)),
    error: color(9, color(1, "#d25050")),
    surfaceVariant: color(0, background),
  };
}

function paletteSource() {
  if (requestedSource === "ryoku") return { type: "ryoku", file: ryokuPalettePath };
  if (requestedSource === "pywal") return { type: "pywal", file: pywalPalettePath };
  if (fs.existsSync(ryokuPalettePath)) return { type: "ryoku", file: ryokuPalettePath };
  if (fs.existsSync(pywalPalettePath)) return { type: "pywal", file: pywalPalettePath };
  throw new Error("no palette found (expected Ryoku or Pywal colors.json)");
}

function palette() {
  const source = paletteSource();
  const document = JSON.parse(fs.readFileSync(source.file, "utf8"));
  return source.type === "pywal" ? pywalToMaterial(document) : document;
}

function render() {
  if (!fs.existsSync(basePath)) return;
  const colors = palette();
  const body = fs.readFileSync(basePath, "utf8");
  const lines = [
    "[wal16]",
    "; Generated by Spiceflow from Ryoku's live wallpaper palette.",
    ...Object.entries(roles).map(([name, role]) => {
      const value = colors[role];
      if (!/^#[0-9a-f]{6}$/i.test(value || "")) throw new Error(`missing palette role ${role}`);
      return `${name.padEnd(19)}= ${value}`;
    }),
  ];
  const section = `${lines.join("\n")}\n`;
  const sectionPattern = /^\[wal16\][\s\S]*?(?=^\[[^\]]+\]\s*$|(?![\s\S]))/m;
  const replaced = sectionPattern.test(body)
    ? body.replace(sectionPattern, section)
    : `${body.trimEnd()}\n\n${section}`;
  const temporary = `${colorPath}.spiceflow-tmp`;
  fs.writeFileSync(temporary, replaced);
  fs.renameSync(temporary, colorPath);
}

let timer;
function scheduleRender() {
  clearTimeout(timer);
  timer = setTimeout(() => {
    try { render(); } catch (error) { console.error(`render: ${error.message}`); }
  }, 100);
}
fs.watchFile(ryokuPalettePath, { interval: 500 }, scheduleRender);
fs.watchFile(pywalPalettePath, { interval: 500 }, scheduleRender);

try { render(); } catch (error) { console.error(`initial render: ${error.message}`); }

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Private-Network": "true",
};

http.createServer((request, response) => {
  if (request.method === "OPTIONS") return response.writeHead(204, cors).end();
  if (!request.url.startsWith("/colors.json")) return response.writeHead(404).end();
  try {
    const data = Buffer.from(JSON.stringify(palette()));
    response.writeHead(200, {
      ...cors,
      "Cache-Control": "no-store",
      "Content-Type": "application/json",
    });
    response.end(data);
  } catch (_) {
    response.writeHead(503, cors).end();
  }
}).listen(port, "127.0.0.1", () => {
  let source = "unavailable";
  try { source = paletteSource().type; } catch (_) {}
  console.log(`Spiceflow listening on http://127.0.0.1:${port} (${source})`);
});
